/// financials
table financials
	lineageTag: f1e7f35e-86a7-4c7e-b382-9c8a80e597c8

	/// Segment
	column Segment
		dataType: string
		lineageTag: e22e97f1-1c9a-4ddf-a9c6-e3d20218b402
		summarizeBy: none
		sourceColumn: Segment
		annotation SummarizationSetBy = Automatic

	/// Country
	column Country
		dataType: string
		lineageTag: 60f63843-aae5-479e-9434-2642d896c72f
		summarizeBy: none
		sourceColumn: Country
		annotation SummarizationSetBy = Automatic

	/// Product
	column Product
		dataType: string
		lineageTag: 0fa5a785-f140-400c-80ad-326a3e13fb53
		summarizeBy: none
		sourceColumn: Product
		annotation SummarizationSetBy = Automatic

	/// Discount Band
	column 'Discount Band'
		dataType: string
		lineageTag: bd4f95b3-3a12-4312-8d30-e84355fbb4b9
		summarizeBy: none
		sourceColumn: Discount Band
		annotation SummarizationSetBy = Automatic

	/// Units Sold
	column 'Units Sold'
		dataType: double
		lineageTag: e3123e33-d89d-4101-8ba5-20116eb324e1
		summarizeBy: sum
		sourceColumn: Units Sold
		annotation SummarizationSetBy = Automatic
		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Manufacturing Price
	column 'Manufacturing Price'
		dataType: int64
		formatString: 0
		lineageTag: 5b3a03ed-a71e-405e-94a7-f6d69e23d9fa
		summarizeBy: sum
		sourceColumn: Manufacturing Price
		annotation SummarizationSetBy = Automatic

	/// Sale Price
	column 'Sale Price'
		dataType: int64
		formatString: 0
		lineageTag: 7e5f2a9d-3091-498f-b4e4-0cbfa1b13393
		summarizeBy: sum
		sourceColumn: Sale Price
		annotation SummarizationSetBy = Automatic

	/// Gross Sales
	column 'Gross Sales'
		dataType: double
		lineageTag: ddf12a46-ca58-4164-be97-7d9018a9726b
		summarizeBy: sum
		sourceColumn: Gross Sales
		annotation SummarizationSetBy = Automatic
		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Discounts
	column Discounts
		dataType: double
		lineageTag: 7ac46e49-a7f6-4c38-bf45-d8a151af107c
		summarizeBy: sum
		sourceColumn: Discounts
		annotation SummarizationSetBy = Automatic
		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// COGS
	column COGS
		dataType: double
		lineageTag: 4c9dd987-455d-464f-b1a4-c1365c261084
		summarizeBy: sum
		sourceColumn: COGS
		annotation SummarizationSetBy = Automatic
		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Profit
	column Profit
		dataType: double
		lineageTag: d62d1576-5d8f-4b2d-b94d-263dea93bcbe
		summarizeBy: sum
		sourceColumn: Profit
		annotation SummarizationSetBy = Automatic
		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Date
	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 38ae31e6-71d7-4ffe-a87c-e7faaa000889
		summarizeBy: none
		sourceColumn: Date
		annotation SummarizationSetBy = Automatic
		annotation UnderlyingDateTimeDataType = Date

	/// Month Number
	column 'Month Number'
		dataType: int64
		formatString: 0
		lineageTag: d9ff2003-7a22-4c93-aaa8-12b7850e076f
		summarizeBy: sum
		sourceColumn: Month Number
		annotation SummarizationSetBy = Automatic

	/// Month Name
	column 'Month Name'
		dataType: string
		lineageTag: ab8576b5-b794-4d37-abc7-3149b4bd1488
		summarizeBy: none
		sourceColumn: Month Name
		annotation SummarizationSetBy = Automatic

	/// Year
	column Year
		dataType: int64
		formatString: 0
		lineageTag: acb8eb50-db4f-43d2-8fb0-75f0483eb408
		summarizeBy: sum
		sourceColumn: Year
		annotation SummarizationSetBy = Automatic

	/// ¡OJO!: columna en origen con espacio inicial
	column ' Sales'
		dataType: double
		lineageTag: c771ce45-f132-4d7d-8624-4d24d1cb3639
		summarizeBy: sum
		sourceColumn: " Sales"
		annotation SummarizationSetBy = Automatic
		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition financials = m
		mode: import
		source =
				let
				 Source = Excel.Workbook(File.Contents("C:\\Code\\DemoPBPIP\\DataSource\\Financial Sample.xlsx"), null, true),
				    financials_Table = Source{[Item="financials",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(
						financials_Table,
						{{"Segment", type text}, {"Country", type text}, {"Product", type text}, {"Discount Band", type text},
						 {"Units Sold", type number}, {"Manufacturing Price", Int64.Type}, {"Sale Price", Int64.Type},
						 {"Gross Sales", type number}, {"Discounts", type number}, {" Sales", type number},
						 {"COGS", type number}, {"Profit", type number}, {"Date", type date},
						 {"Month Number", Int64.Type}, {"Month Name", type text}, {"Year", Int64.Type}}
					)
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
	annotation PBI_NavigationStepName = Navigation
