table MyDateTable
	lineageTag: a9888d5e-9a85-448f-b47b-9b8c90ee913b

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: adcd1fdb-2591-4d67-8e2b-4131ba676b4b
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 9e9377c0-e524-446f-b446-6ee1f2a6cccf
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 8263516d-b7bd-439f-8123-fa69dee7066d
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		formatString: 0
		lineageTag: a1cdd249-ac65-4277-ad27-928370715403
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 89e9e3ee-88dc-4fe3-b3c2-ac0b0b1e77d6
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column PeriodWeek
		dataType: int64
		formatString: 0
		lineageTag: 849fbe03-9c15-4816-b815-4a3258b55b2f
		summarizeBy: none
		sourceColumn: PeriodWeek

		annotation SummarizationSetBy = Automatic

	column PeriodCampaign
		dataType: string
		lineageTag: 06b6e7fe-9927-44b0-9602-9d417f6e4a8f
		summarizeBy: none
		sourceColumn: PeriodCampaign

		annotation SummarizationSetBy = Automatic

	column PeriodCampaignWeek
		dataType: int64
		formatString: 0
		lineageTag: f0035e2a-fdfb-43ef-b11e-22167b51ba38
		summarizeBy: none
		sourceColumn: PeriodCampaignWeek

		annotation SummarizationSetBy = Automatic

	column FiscalYear
		dataType: int64
		formatString: 0
		lineageTag: eaf4deef-308d-4628-a79a-54714fcd7979
		summarizeBy: none
		sourceColumn: FiscalYear

		annotation SummarizationSetBy = Automatic

	column Id
		dataType: int64
		formatString: 0
		lineageTag: f37ad915-9b25-4d57-9ade-6b35913ed339
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column MonthInLetters
		dataType: string
		lineageTag: 7080a7fb-1655-4883-b944-030c3a228498
		summarizeBy: none
		sourceColumn: MonthInLetters

		annotation SummarizationSetBy = Automatic

	partition MyDateTable = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents(DSPath & "Financial Sample.xlsx"), null, true),
				    MyDateTable_Sheet = Source{[Item="MyDateTable",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(MyDateTable_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Year", Int64.Type}, {"Month", Int64.Type}, {"Day", Int64.Type}, {"Quarter", type text}, {"PeriodWeek", Int64.Type}, {"PeriodCampaign", type text}, {"PeriodCampaignWeek", Int64.Type}, {"FiscalYear", Int64.Type}, {"Id", Int64.Type}, {"MonthInLetters", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

